---
# This playbook will install mysql and create db user and give permissions.

- name: Install mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - mysql-client

- apt: pkg=python-mysqldb state=installed

- name: Create mysql log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  
- name: Start mysql Service
  service: name=mysql state=started enabled=yes

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv=*.*:ALL,GRANT host=% state=present

- name: Update bind-host
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line='bind-address            = 0.0.0.0'

- service: name=mysql state=restarted