---
- name: Create Launch Configuration
  ec2_lc:
    region: "{{ aws_region }}"
    name: "webapp-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
    image_id: "{{ ami.image_id }}"
    key_name: "{{ key_pair }}"
    instance_type: "{{ instance_type }}"
    security_groups: [ sg-27e88841, sg-2ce8884a, sg-22e88844, sg-5ee88838 ]
    assign_public_ip: yes
    
