---
- name: Create VPC
  ec2_vpc:
    state: present
    cidr_block: 172.22.0.0/16
    resource_tags: { "Environment":"{{ env }}" }
    internet_gateway: True
    subnets:
      - cidr: 172.22.1.0/24
        az: "{{ az_web }}"
        resource_tags: { "env":"demo", "type" : "web" }
      - cidr: 172.22.2.0/24
        az: "{{ az_db }}"
        resource_tags: { "env":"demo", "type" : "database" }
    route_tables:
      - subnets:
        - 172.22.1.0/24
        - 172.22.2.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    region: "{{ aws_region }}"
  register: vpc

- name: save vpc_id
  set_fact: vpc_id={{ vpc.vpc_id }}
